### ISSUE TITLE
Breaks shortcut du go to end of line

### ISSUE THREAD

**Issue by trenkwill** [rmaksim/Sublime-Text-2-Goto-CSS-Declaration#11]
Hi !
The plugins breaks the shortcut du go to end of line (cmd + right arrow) on Mac. I've tried to change the shortcut in the plugins preference which works (I did ctrl + cmd + right arrow) but it doesn't put back the original system shortcut :(

Any idea on how to fix this?

Thanks! 

William

**Comment by gggauravgandhi** [comment]
Facing same problem, thus removed plugin mean while.
Do fix this or guide on how to fix this. 

I already setup new key-binding but old binding is till there, hence line-end shortcut over-written, which imo is more needed.

Anyway thanks for nice plugin.

**Comment by rmaksim** [comment]
Hello
try as they say in the comments https://github.com/rmaksim/Sublime-Text-2-Goto-CSS-Declaration/issues/1#issuecomment-7896568 https://github.com/rmaksim/Sublime-Text-2-Goto-CSS-Declaration/issues/1#issuecomment-10403923

**Comment by gggauravgandhi** [comment]
It doesn;t help removing default bindings.

**Comment by trenkwill** [comment]
Yes even after changing the key biding it stills blocks the default OS X one.

**Comment by rmaksim** [comment]
You make changes directly in the file https://github.com/rmaksim/Sublime-Text-2-Goto-CSS-Declaration/blob/master/Default%20(OSX).sublime-keymap ?

**Comment by gggauravgandhi** [comment]
It's read only file. 
I am using ST3.

**Comment by trenkwill** [comment]
Yes I copy pasted the default key bindings into my own (user) key binding file. Changed it to super+0 for next and super+9 to prev. They work but it doesn't give me back the default OS X key bindings to go to the end of line :(

**Comment by rmaksim** [comment]
I do not have the opportunity to test on the Mac.
I can change the default settings and download them to git.
What are your suggestions for change for Mac?

**Comment by gggauravgandhi** [comment]
I suggest `ctrl+super+left` and `ctrl+super+right`

**Comment by trenkwill** [comment]
I wonder if just adding "ctrl" to the ones you would break the os x default

**Comment by trenkwill** [comment]
yep just as @gggauravgandhi just said.

**Comment by trenkwill** [comment]
wasn't it already the case before ? I remember using that key biding some time ago :)

**Comment by gggauravgandhi** [comment]
I never used that, and its not any system-wide key-bindings. So we are safe for now. :)

**Comment by trenkwill** [comment]
thanks @rmaksim, this plugin rocks!

**Comment by gggauravgandhi** [comment]
thanks @rmaksim 
Just remove and installed again, working as desired.
Thanks again.

if you need help in future for testing something on mac, then i can help.

**Comment by trenkwill** [comment]
yes same here, I'd be happy to help!

**Comment by rmaksim** [comment]
ok, thanks, closed ;)
